Widget media broken link in Django 3 (#75)
ValueError: Missing staticfiles manifest entry for 'material/admin/js/widgets//DateInput.js' in Django 3 + whitenoise when debug is False.
Removing extra slash from the link